--- 
version: "2.4"
services:

  kafka-zoo1:
    extends:
      file: ae-services/kafka/kafka-zoo1.yaml
      service: kafka-zoo1
  kafka-zoo2:
    extends:
      file: ae-services/kafka/kafka-zoo2.yaml
      service: kafka-zoo2
  kafka-zoo3:
    extends:
      file: ae-services/kafka/kafka-zoo3.yaml
      service: kafka-zoo3
  kafka: 
    extends: 
      file: ae-services/kafka/kafka.yaml
      service: kafka
    depends_on:
      - kafka-zoo1
      - kafka-zoo2
      - kafka-zoo3
  kafka-ui:
    extends:
      file: services/kafka/kafka-ui.yaml
      service: kafka-ui
    depends_on:
      - kafka-zoo1
      - kafka-zoo2
      - kafka-zoo3
      - kafka

  postgres: 
    extends: 
      file: ae-services/postgres.yaml
      service: postgres
