--- 
version: "2.4"
services: 
  postgres:
    container_name: postgres-$POSTGRES_VERSION
    environment: 
      LC_ALL: en_US.UTF-8
      LC_CTYPE: en_US.UTF-8
      PG_DATA: /pg
      POSTGRES_DB: ae
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: ae
    healthcheck: 
      interval: 3s
      retries: 10
      test: 
        - CMD
        - "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"
      timeout: 2s
    image: "postgres:$POSTGRES_VERSION"
    ports: 
      - "5432:5432"
    volumes: 
      - "./postgres-tables/initdb.d:/docker-entrypoint-initdb.d:ro"
