version: "2.1"
services:
  kafka-zoo2:
    image: confluentinc/cp-zookeeper:$KAFKA_VERSION
    hostname: kafka-zoo2
    container_name: kafka-zoo2-$KAFKA_VERSION
    ports:
      - "2182:2182"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2182
      ZOOKEEPER_SERVER_ID: 2
      ZOOKEEPER_SERVERS: kafka-zoo1:2888:3888;kafka-zoo2:2888:3888;kafka-zoo3:2888:3888